# bundle exec rubocop -f html > report.html

require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  NewCops: enable
  DisplayCopNames: true
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
# インデントをgofmtっぽくそろえる
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false
# トップレベルのクラスのドキュメントコメントがありませんを無効化
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/Lambda:
  EnforcedStyle: literal
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": ()
    "%I": ()
    "%r": ()
    "%w": ()
    "%W": ()
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/RescueStandardError:
  EnforcedStyle: implicit
# 日本語対応
RSpec/ContextWording:
  Enabled: false
